Packages
jscrates/packages pull request #1
Opened 2021-12-08 14:28 UTC by Jarvis2001

Added package-meta for formulas and factorial

2021-12-08 22:11 UTC, Jarvis2001 commented
Function content added in factorial.js and formulas.js since the calculation is based on BODMAS package sample calculation functions(mul, div, sqr, pow) are inserted instead of actual BODMAS(yet to be developed) functions.

2021-12-10 08:52 UTC, Jarvis2001 commented
Added return statement in formulas and factorial

2021-12-11 05:56 UTC, kasipavankumar requested changes
Please make the requested changes.

2021-12-11 05:56 UTC, kasipavankumar commented on packages/factorial/factorial.js
> +export default function factorial() {
Please change this to `module.exports` as we cannot use `export default` here.
```js
module.exports = function factorial() {}
```

2021-12-11 05:56 UTC, kasipavankumar commented on packages/formulas/formulas.js
> +export function spd(){
Remove `export` from all the functions & at the end of the file add the following code:
```js
module.exports = {
  spd,
  acc,
  momen,
  // Add all the function names here
}
```

2021-12-11 06:10 UTC, kasipavankumar approved these changes
LGTM!

2021-12-11 06:10 UTC, merged